enableTransparentWorkspaces: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "@yarnpkg/plugin-constraints"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-sources.js
