enableTransparentWorkspaces: false

# This is mostly needed for Flow support.
# See https://github.com/yarnpkg/berry/issues/634
nodeLinker: node-modules

unsafeHttpWhitelist:
 - localhost # Used by verdaccio

yarnPath: .yarn/releases/yarn-sources.js
